### ISSUE TITLE
registration error on Magento 2.1.8

### ISSUE THREAD

**Issue by gediminaskv** [magekey/module-customer-restriction#2]
> URL: http://[domain]/checkout/account/create
> IP Address: xxx.xxx.xxx.xxx
> Time: 2018-03-19 12:47:16 GMT
> Error:
> Warning: preg_match(): Compilation failed: nothing to repeat at offset 0 in /home/[domain]/public_html/vendor/magekey/module-customer-restriction/Model/Restriction/Filter.php on line 18

I noticed that it's impossible to create an account even if you do not meet the restrictions setting: https://prnt.sc/it9hyk

EDIT: it was my incorrect settings. Pattern must be just a domain, for instance, sina.com. No special chars like `*` or `@`

**Comment by magekey** [comment]
Added fixes to prevent pattern errors. Released 2.1.2.
